export type Language = {
    code: string;
    name: string;
};

export type Phrase = {
    id: string;
    categoryId: string;
    targetText: string;
    translation: string; // always Japanese translation in this MVP
};

export type Category = {
    id: string;
    name: string;
};

export const LANGUAGES: Language[] = [
    { code: "en", name: "English" },
    { code: "ko", name: "Korean" },
    { code: "ja", name: "Japanese" },

    { code: "es", name: "Spanish" },
    { code: "fr", name: "French" },
    { code: "de", name: "German" },
    { code: "it", name: "Italian" },
    { code: "pt", name: "Portuguese" },
    { code: "ru", name: "Russian" },
    { code: "zh", name: "Chinese (Simplified)" },
    { code: "ar", name: "Arabic" },
    { code: "hi", name: "Hindi" },
    { code: "th", name: "Thai" },
    { code: "vi", name: "Vietnamese" },
    { code: "id", name: "Indonesian" },
    { code: "tr", name: "Turkish" },
    { code: "nl", name: "Dutch" },
    { code: "sv", name: "Swedish" },
    { code: "pl", name: "Polish" },
];

export const CATEGORIES: Category[] = [
    { id: "greeting", name: "Greeting" },
    { id: "dining", name: "Dining" },
    { id: "travel", name: "Travel" },
    { id: "emotions", name: "Emotions" },
];

// Mapping to Gemini 2.5 Pro Preview TTS Locales
export const LANGUAGE_LOCALES: Record<string, string> = {
    ar: "ar-EG", // Arabic (Egyptian)
    de: "de-DE", // German (Germany)
    en: "en-US", // English (US)
    es: "es-US", // Spanish (US) - Note: User specified US, previously ES
    fr: "fr-FR", // French (France)
    hi: "hi-IN", // Hindi (India)
    id: "id-ID", // Indonesian (Indonesia)
    it: "it-IT", // Italian (Italy)
    ja: "ja-JP", // Japanese (Japan)
    ko: "ko-KR", // Korean (Korea)
    pt: "pt-BR", // Portuguese (Brazil)
    ru: "ru-RU", // Russian (Russia)
    nl: "nl-NL", // Dutch (Netherlands)
    pl: "pl-PL", // Polish (Poland)
    th: "th-TH", // Thai (Thailand)
    tr: "tr-TR", // Turkish (Turkey)
    vi: "vi-VN", // Vietnamese (Vietnam)
    ro: "ro-RO", // Romanian (Romania)
    uk: "uk-UA", // Ukrainian (Ukraine)
    bn: "bn-BD", // Bengali (Bangladesh)
    mr: "mr-IN", // Marathi (India)
    ta: "ta-IN", // Tamil (India)
    te: "te-IN", // Telugu (India)
    // Fallbacks or others from previous list if needed, but user list seems comprehensive for the model support
    zh: "cmn-CN", // Keep Chinese as is (not in user list but good to have fallback/standard)
    sv: "sv-SE", // Keep Swedish
};

/**
 * Japanese translations (source of truth) — 20 per category
 * Keep these aligned with every language’s target strings (same index = same meaning).
 */
const JP: Record<string, string[]> = {
    greeting: [
        "こんにちは。",
        "おはよう。",
        "こんばんは。",
        "はじめまして。",
        "久しぶり。",
        "元気？",
        "元気です。",
        "ありがとう。",
        "すみません。",
        "お願いします。",
        "もう一度言ってください。",
        "ゆっくり話してください。",
        "分かりました。",
        "分かりません。",
        "助けてください。",
        "お名前は？",
        "私は〜です。",
        "またね。",
        "気をつけて。",
        "よろしくお願いします。",
    ],
    dining: [
        "メニューをください。",
        "水をください。",
        "これをください。",
        "おすすめは何ですか？",
        "これは辛いですか？",
        "辛くしないでください。",
        "お会計お願いします。",
        "カードは使えますか？",
        "レシートください。",
        "持ち帰りできますか？",
        "おいしいです。",
        "お腹いっぱいです。",
        "ベジタリアンです。",
        "アレルギーがあります。",
        "肉なしでお願いします。",
        "玉ねぎなしでお願いします。",
        "もう一つください。",
        "予約しています。",
        "2人です。",
        "乾杯。",
    ],
    travel: [
        "トイレはどこですか？",
        "駅はどこですか？",
        "ここへどう行きますか？",
        "私は道に迷いました。",
        "地図で見せてください。",
        "どれくらいかかりますか？",
        "チケットをください。",
        "チケット2枚ください。",
        "何時ですか？",
        "何時に出発しますか？",
        "タクシーを呼んでください。",
        "ここで降ろしてください。",
        "ホテルはどこですか？",
        "入口はどこですか？",
        "出口はどこですか？",
        "まっすぐ行ってください。",
        "左に曲がってください。",
        "右に曲がってください。",
        "写真を撮ってください。",
        "いくらですか？",
    ],
    emotions: [
        "うれしいです。",
        "悲しいです。",
        "疲れました。",
        "眠いです。",
        "お腹すきました。",
        "のどが渇きました。",
        "緊張しています。",
        "心配です。",
        "怒っています。",
        "びっくりしました。",
        "怖いです。",
        "退屈です。",
        "さみしいです。",
        "ストレスがあります。",
        "大丈夫です。",
        "大丈夫じゃないです。",
        "好きです。",
        "好きじゃないです。",
        "会いたいです。",
        "落ち着いています。",
    ],
};

/**
 * Target texts: 20 per category, per language
 * NOTE: Keep order aligned with JP[category].
 */
const TARGET: Record<string, Record<string, string[]>> = {
    // --- English ---
    en: {
        greeting: [
            "Hello.",
            "Good morning.",
            "Good evening.",
            "Nice to meet you.",
            "Long time no see.",
            "How are you?",
            "I’m good.",
            "Thank you.",
            "Sorry.",
            "Please.",
            "Please say that again.",
            "Please speak slowly.",
            "I understand.",
            "I don’t understand.",
            "Help me, please.",
            "What’s your name?",
            "I’m ____.",
            "See you.",
            "Take care.",
            "Nice to meet you.",
        ],
        dining: [
            "Could I have the menu, please?",
            "Water, please.",
            "This one, please.",
            "What do you recommend?",
            "Is this spicy?",
            "Not spicy, please.",
            "Could we get the bill, please?",
            "Can I pay by card?",
            "A receipt, please.",
            "To go, please.",
            "It’s delicious.",
            "I’m full.",
            "I’m vegetarian.",
            "I have an allergy.",
            "No meat, please.",
            "No onions, please.",
            "One more, please.",
            "I have a reservation.",
            "Table for two, please.",
            "Cheers.",
        ],
        travel: [
            "Where is the restroom?",
            "Where is the station?",
            "How do I get there?",
            "I’m lost.",
            "Could you show me on the map?",
            "How long does it take?",
            "A ticket, please.",
            "Two tickets, please.",
            "What time is it?",
            "What time does it leave?",
            "Could you call a taxi, please?",
            "Please drop me off here.",
            "Where is the hotel?",
            "Where is the entrance?",
            "Where is the exit?",
            "Go straight, please.",
            "Turn left, please.",
            "Turn right, please.",
            "Could you take a photo, please?",
            "How much is it?",
        ],
        emotions: [
            "I’m happy.",
            "I’m sad.",
            "I’m tired.",
            "I’m sleepy.",
            "I’m hungry.",
            "I’m thirsty.",
            "I’m nervous.",
            "I’m worried.",
            "I’m angry.",
            "I’m surprised.",
            "I’m scared.",
            "I’m bored.",
            "I’m lonely.",
            "I’m stressed.",
            "I’m okay.",
            "I’m not okay.",
            "I like it.",
            "I don’t like it.",
            "I miss you.",
            "I feel calm.",
        ],
    },

    // --- Korean (polite, beginner) ---
    ko: {
        greeting: [
            "안녕하세요.",
            "좋은 아침이에요.",
            "안녕하세요.",
            "처음 뵙겠습니다.",
            "오랜만이에요.",
            "잘 지내요?",
            "잘 지내요.",
            "감사합니다.",
            "죄송합니다.",
            "부탁해요.",
            "다시 말해 주세요.",
            "천천히 말해 주세요.",
            "알겠어요.",
            "잘 모르겠어요.",
            "도와 주세요.",
            "이름이 뭐예요?",
            "저는 ____예요.",
            "또 봐요.",
            "조심히 가세요.",
            "잘 부탁드려요.",
        ],
        dining: [
            "메뉴판 주세요.",
            "물 주세요.",
            "이거 주세요.",
            "추천은 뭐예요?",
            "이거 매워요?",
            "안 맵게 해 주세요.",
            "계산할게요.",
            "카드 돼요?",
            "영수증 주세요.",
            "포장 가능해요?",
            "맛있어요.",
            "배불러요.",
            "저는 채식이에요.",
            "알레르기가 있어요.",
            "고기 빼 주세요.",
            "양파 빼 주세요.",
            "하나 더 주세요.",
            "예약했어요.",
            "두 명이에요.",
            "건배.",
        ],
        travel: [
            "화장실이 어디예요?",
            "역이 어디예요?",
            "여기 어떻게 가요?",
            "길을 잃었어요.",
            "지도에서 보여 주세요.",
            "얼마나 걸려요?",
            "표 주세요.",
            "표 두 장 주세요.",
            "지금 몇 시예요?",
            "몇 시에 출발해요?",
            "택시 불러 주세요.",
            "여기서 내려 주세요.",
            "호텔이 어디예요?",
            "입구가 어디예요?",
            "출구가 어디예요?",
            "직진해 주세요.",
            "왼쪽으로 가 주세요.",
            "오른쪽으로 가 주세요.",
            "사진 찍어 주세요.",
            "얼마예요?",
        ],
        emotions: [
            "기뻐요.",
            "슬퍼요.",
            "피곤해요.",
            "졸려요.",
            "배고파요.",
            "목말라요.",
            "긴장돼요.",
            "걱정돼요.",
            "화가 나요.",
            "깜짝 놀랐어요.",
            "무서워요.",
            "심심해요.",
            "외로워요.",
            "스트레스 받아요.",
            "괜찮아요.",
            "괜찮지 않아요.",
            "좋아해요.",
            "별로예요.",
            "보고 싶어요.",
            "진정됐어요.",
        ],
    },

    // --- Japanese (translation same, for compatibility) ---
    ja: {
        greeting: [...JP.greeting],
        dining: [...JP.dining],
        travel: [...JP.travel],
        emotions: [...JP.emotions],
    },

    // --- Spanish ---
    es: {
        greeting: [
            "Hola.",
            "Buenos días.",
            "Buenas noches.",
            "Mucho gusto.",
            "Cuánto tiempo.",
            "¿Cómo estás?",
            "Estoy bien.",
            "Gracias.",
            "Perdón.",
            "Por favor.",
            "¿Puedes repetirlo?",
            "Habla más despacio, por favor.",
            "Entiendo.",
            "No entiendo.",
            "Ayúdame, por favor.",
            "¿Cómo te llamas?",
            "Soy ____.",
            "Nos vemos.",
            "Cuídate.",
            "Encantado/a.",
        ],
        dining: [
            "El menú, por favor.",
            "Agua, por favor.",
            "Esto, por favor.",
            "¿Qué recomiendas?",
            "¿Esto pica?",
            "Sin picante, por favor.",
            "La cuenta, por favor.",
            "¿Puedo pagar con tarjeta?",
            "El recibo, por favor.",
            "Para llevar, por favor.",
            "Está delicioso.",
            "Estoy lleno/a.",
            "Soy vegetariano/a.",
            "Tengo alergia.",
            "Sin carne, por favor.",
            "Sin cebolla, por favor.",
            "Uno más, por favor.",
            "Tengo una reserva.",
            "Somos dos.",
            "Salud.",
        ],
        travel: [
            "¿Dónde está el baño?",
            "¿Dónde está la estación?",
            "¿Cómo llego aquí?",
            "Estoy perdido/a.",
            "Muéstramelo en el mapa, por favor.",
            "¿Cuánto tarda?",
            "Un billete, por favor.",
            "Dos billetes, por favor.",
            "¿Qué hora es?",
            "¿A qué hora sale?",
            "Llame un taxi, por favor.",
            "Déjeme aquí, por favor.",
            "¿Dónde está el hotel?",
            "¿Dónde está la entrada?",
            "¿Dónde está la salida?",
            "Siga recto, por favor.",
            "Gire a la izquierda, por favor.",
            "Gire a la derecha, por favor.",
            "¿Puede tomar una foto, por favor?",
            "¿Cuánto cuesta?",
        ],
        emotions: [
            "Estoy feliz.",
            "Estoy triste.",
            "Estoy cansado/a.",
            "Tengo sueño.",
            "Tengo hambre.",
            "Tengo sed.",
            "Estoy nervioso/a.",
            "Estoy preocupado/a.",
            "Estoy enojado/a.",
            "Estoy sorprendido/a.",
            "Tengo miedo.",
            "Estoy aburrido/a.",
            "Me siento solo/a.",
            "Estoy estresado/a.",
            "Estoy bien.",
            "No estoy bien.",
            "Me gusta.",
            "No me gusta.",
            "Te extraño.",
            "Estoy tranquilo/a.",
        ],
    },

    // --- French ---
    fr: {
        greeting: [
            "Bonjour.",
            "Bonjour.",
            "Bonsoir.",
            "Enchanté(e).",
            "Ça fait longtemps.",
            "Ça va ?",
            "Ça va.",
            "Merci.",
            "Pardon.",
            "S’il vous plaît.",
            "Vous pouvez répéter ?",
            "Parlez plus lentement, s’il vous plaît.",
            "Je comprends.",
            "Je ne comprends pas.",
            "Aidez-moi, s’il vous plaît.",
            "Comment vous appelez-vous ?",
            "Je m’appelle ____.",
            "À bientôt.",
            "Prenez soin de vous.",
            "Ravi(e) de vous rencontrer.",
        ],
        dining: [
            "Le menu, s’il vous plaît.",
            "De l’eau, s’il vous plaît.",
            "Ça, s’il vous plaît.",
            "Vous recommandez quoi ?",
            "C’est épicé ?",
            "Pas épicé, s’il vous plaît.",
            "L’addition, s’il vous plaît.",
            "Je peux payer par carte ?",
            "Le reçu, s’il vous plaît.",
            "À emporter, s’il vous plaît.",
            "C’est délicieux.",
            "Je suis rassasié(e).",
            "Je suis végétarien(ne).",
            "J’ai une allergie.",
            "Sans viande, s’il vous plaît.",
            "Sans oignons, s’il vous plaît.",
            "Encore un, s’il vous plaît.",
            "J’ai une réservation.",
            "Nous sommes deux.",
            "Santé.",
        ],
        travel: [
            "Où sont les toilettes ?",
            "Où est la gare ?",
            "Comment je vais ici ?",
            "Je suis perdu(e).",
            "Montrez-moi sur la carte, s’il vous plaît.",
            "Ça prend combien de temps ?",
            "Un billet, s’il vous plaît.",
            "Deux billets, s’il vous plaît.",
            "Quelle heure est-il ?",
            "À quelle heure ça part ?",
            "Appelez un taxi, s’il vous plaît.",
            "Déposez-moi ici, s’il vous plaît.",
            "Où est l’hôtel ?",
            "Où est l’entrée ?",
            "Où est la sortie ?",
            "Tout droit, s’il vous plaît.",
            "Tournez à gauche, s’il vous plaît.",
            "Tournez à droite, s’il vous plaît.",
            "Vous pouvez prendre une photo ?",
            "C’est combien ?",
        ],
        emotions: [
            "Je suis heureux/heureuse.",
            "Je suis triste.",
            "Je suis fatigué(e).",
            "J’ai sommeil.",
            "J’ai faim.",
            "J’ai soif.",
            "Je suis stressé(e).",
            "Je m’inquiète.",
            "Je suis en colère.",
            "Je suis surpris(e).",
            "J’ai peur.",
            "Je m’ennuie.",
            "Je me sens seul(e).",
            "Je suis sous pression.",
            "Ça va.",
            "Ça ne va pas.",
            "J’aime ça.",
            "Je n’aime pas ça.",
            "Tu me manques.",
            "Je suis calme.",
        ],
    },

    // --- German ---
    de: {
        greeting: [
            "Hallo.",
            "Guten Morgen.",
            "Guten Abend.",
            "Freut mich.",
            "Lange nicht gesehen.",
            "Wie geht’s?",
            "Mir geht’s gut.",
            "Danke.",
            "Entschuldigung.",
            "Bitte.",
            "Können Sie das wiederholen?",
            "Bitte sprechen Sie langsam.",
            "Ich verstehe.",
            "Ich verstehe nicht.",
            "Helfen Sie mir, bitte.",
            "Wie heißen Sie?",
            "Ich heiße ____.",
            "Bis später.",
            "Pass auf dich auf.",
            "Schön, Sie kennenzulernen.",
        ],
        dining: [
            "Die Speisekarte, bitte.",
            "Wasser, bitte.",
            "Das hier, bitte.",
            "Was empfehlen Sie?",
            "Ist das scharf?",
            "Nicht scharf, bitte.",
            "Die Rechnung, bitte.",
            "Kann ich mit Karte zahlen?",
            "Die Quittung, bitte.",
            "Zum Mitnehmen, bitte.",
            "Es ist lecker.",
            "Ich bin satt.",
            "Ich bin Vegetarier/in.",
            "Ich habe eine Allergie.",
            "Ohne Fleisch, bitte.",
            "Ohne Zwiebeln, bitte.",
            "Noch eins, bitte.",
            "Ich habe reserviert.",
            "Wir sind zu zweit.",
            "Prost.",
        ],
        travel: [
            "Wo ist die Toilette?",
            "Wo ist der Bahnhof?",
            "Wie komme ich hierhin?",
            "Ich habe mich verlaufen.",
            "Zeigen Sie es auf der Karte, bitte.",
            "Wie lange dauert es?",
            "Eine Fahrkarte, bitte.",
            "Zwei Fahrkarten, bitte.",
            "Wie spät ist es?",
            "Wann fährt es ab?",
            "Rufen Sie ein Taxi, bitte.",
            "Hier bitte anhalten.",
            "Wo ist das Hotel?",
            "Wo ist der Eingang?",
            "Wo ist der Ausgang?",
            "Geradeaus, bitte.",
            "Links abbiegen, bitte.",
            "Rechts abbiegen, bitte.",
            "Können Sie ein Foto machen?",
            "Wie viel kostet das?",
        ],
        emotions: [
            "Ich bin glücklich.",
            "Ich bin traurig.",
            "Ich bin müde.",
            "Ich bin schläfrig.",
            "Ich habe Hunger.",
            "Ich habe Durst.",
            "Ich bin nervös.",
            "Ich mache mir Sorgen.",
            "Ich bin wütend.",
            "Ich bin überrascht.",
            "Ich habe Angst.",
            "Mir ist langweilig.",
            "Ich fühle mich einsam.",
            "Ich bin gestresst.",
            "Mir geht’s gut.",
            "Mir geht’s nicht gut.",
            "Ich mag das.",
            "Ich mag das nicht.",
            "Ich vermisse dich.",
            "Ich bin ruhig.",
        ],
    },

    // --- Italian ---
    it: {
        greeting: [
            "Ciao.",
            "Buongiorno.",
            "Buonasera.",
            "Piacere.",
            "Da quanto tempo.",
            "Come stai?",
            "Sto bene.",
            "Grazie.",
            "Scusa.",
            "Per favore.",
            "Puoi ripetere?",
            "Parla più lentamente, per favore.",
            "Capisco.",
            "Non capisco.",
            "Aiutami, per favore.",
            "Come ti chiami?",
            "Mi chiamo ____.",
            "A dopo.",
            "Abbi cura di te.",
            "Molto piacere.",
        ],
        dining: [
            "Il menù, per favore.",
            "Acqua, per favore.",
            "Questo, per favore.",
            "Cosa consigli?",
            "È piccante?",
            "Non piccante, per favore.",
            "Il conto, per favore.",
            "Posso pagare con carta?",
            "La ricevuta, per favore.",
            "Da asporto, per favore.",
            "È delizioso.",
            "Sono pieno/a.",
            "Sono vegetariano/a.",
            "Ho un’allergia.",
            "Senza carne, per favore.",
            "Senza cipolla, per favore.",
            "Ancora uno, per favore.",
            "Ho una prenotazione.",
            "Siamo in due.",
            "Cin cin.",
        ],
        travel: [
            "Dov’è il bagno?",
            "Dov’è la stazione?",
            "Come arrivo qui?",
            "Mi sono perso/a.",
            "Me lo mostra sulla mappa?",
            "Quanto tempo ci vuole?",
            "Un biglietto, per favore.",
            "Due biglietti, per favore.",
            "Che ore sono?",
            "A che ora parte?",
            "Chiami un taxi, per favore.",
            "Mi lasci qui, per favore.",
            "Dov’è l’hotel?",
            "Dov’è l’ingresso?",
            "Dov’è l’uscita?",
            "Dritto, per favore.",
            "Giri a sinistra, per favore.",
            "Giri a destra, per favore.",
            "Può fare una foto?",
            "Quanto costa?",
        ],
        emotions: [
            "Sono felice.",
            "Sono triste.",
            "Sono stanco/a.",
            "Ho sonno.",
            "Ho fame.",
            "Ho sete.",
            "Sono nervoso/a.",
            "Sono preoccupato/a.",
            "Sono arrabbiato/a.",
            "Sono sorpreso/a.",
            "Ho paura.",
            "Mi annoio.",
            "Mi sento solo/a.",
            "Sono stressato/a.",
            "Sto bene.",
            "Non sto bene.",
            "Mi piace.",
            "Non mi piace.",
            "Mi manchi.",
            "Sono calmo/a.",
        ],
    },

    // --- Portuguese ---
    pt: {
        greeting: [
            "Olá.",
            "Bom dia.",
            "Boa noite.",
            "Prazer.",
            "Quanto tempo.",
            "Tudo bem?",
            "Tudo bem.",
            "Obrigado/a.",
            "Desculpe.",
            "Por favor.",
            "Pode repetir?",
            "Fale mais devagar, por favor.",
            "Eu entendo.",
            "Eu não entendo.",
            "Ajude-me, por favor.",
            "Qual é o seu nome?",
            "Eu sou ____.",
            "Até mais.",
            "Cuide-se.",
            "Muito prazer.",
        ],
        dining: [
            "O cardápio, por favor.",
            "Água, por favor.",
            "Isto, por favor.",
            "O que você recomenda?",
            "Isso é apimentado?",
            "Sem pimenta, por favor.",
            "A conta, por favor.",
            "Posso pagar com cartão?",
            "O recibo, por favor.",
            "Para viagem, por favor.",
            "Está delicioso.",
            "Estou cheio/a.",
            "Sou vegetariano/a.",
            "Tenho alergia.",
            "Sem carne, por favor.",
            "Sem cebola, por favor.",
            "Mais um, por favor.",
            "Tenho uma reserva.",
            "Somos dois.",
            "Saúde.",
        ],
        travel: [
            "Onde fica o banheiro?",
            "Onde fica a estação?",
            "Como eu chego aqui?",
            "Estou perdido/a.",
            "Mostre no mapa, por favor.",
            "Quanto tempo leva?",
            "Um bilhete, por favor.",
            "Dois bilhetes, por favor.",
            "Que horas são?",
            "A que horas sai?",
            "Chame um táxi, por favor.",
            "Pare aqui, por favor.",
            "Onde fica o hotel?",
            "Onde é a entrada?",
            "Onde é a saída?",
            "Siga em frente, por favor.",
            "Vire à esquerda, por favor.",
            "Vire à direita, por favor.",
            "Pode tirar uma foto?",
            "Quanto custa?",
        ],
        emotions: [
            "Estou feliz.",
            "Estou triste.",
            "Estou cansado/a.",
            "Estou com sono.",
            "Estou com fome.",
            "Estou com sede.",
            "Estou nervoso/a.",
            "Estou preocupado/a.",
            "Estou com raiva.",
            "Estou surpreso/a.",
            "Estou com medo.",
            "Estou entediado/a.",
            "Estou sozinho/a.",
            "Estou estressado/a.",
            "Estou bem.",
            "Não estou bem.",
            "Eu gosto.",
            "Eu não gosto.",
            "Sinto sua falta.",
            "Estou calmo/a.",
        ],
    },

    // --- Russian ---
    ru: {
        greeting: [
            "Здравствуйте.",
            "Доброе утро.",
            "Добрый вечер.",
            "Приятно познакомиться.",
            "Давно не виделись.",
            "Как дела?",
            "У меня всё хорошо.",
            "Спасибо.",
            "Извините.",
            "Пожалуйста.",
            "Повторите, пожалуйста.",
            "Говорите медленнее, пожалуйста.",
            "Понимаю.",
            "Не понимаю.",
            "Помогите, пожалуйста.",
            "Как вас зовут?",
            "Меня зовут ____.",
            "До встречи.",
            "Берегите себя.",
            "Очень приятно.",
        ],
        dining: [
            "Меню, пожалуйста.",
            "Воду, пожалуйста.",
            "Это, пожалуйста.",
            "Что вы посоветуете?",
            "Это острое?",
            "Не остро, пожалуйста.",
            "Счёт, пожалуйста.",
            "Можно оплатить картой?",
            "Чек, пожалуйста.",
            "С собой, пожалуйста.",
            "Очень вкусно.",
            "Я сыт/сыта.",
            "Я вегетарианец/вегетарианка.",
            "У меня аллергия.",
            "Без мяса, пожалуйста.",
            "Без лука, пожалуйста.",
            "Ещё один, пожалуйста.",
            "У меня бронь.",
            "Нас двое.",
            "За здоровье.",
        ],
        travel: [
            "Где туалет?",
            "Где вокзал?",
            "Как мне туда добраться?",
            "Я заблудился/заблудилась.",
            "Покажите на карте, пожалуйста.",
            "Сколько времени это займет?",
            "Билет, пожалуйста.",
            "Два билета, пожалуйста.",
            "Который час?",
            "Во сколько отправление?",
            "Вызовите такси, пожалуйста.",
            "Остановите здесь, пожалуйста.",
            "Где отель?",
            "Где вход?",
            "Где выход?",
            "Прямо, пожалуйста.",
            "Налево, пожалуйста.",
            "Направо, пожалуйста.",
            "Сфотографируйте, пожалуйста.",
            "Сколько стоит?",
        ],
        emotions: [
            "Я рад/рада.",
            "Мне грустно.",
            "Я устал/устала.",
            "Мне хочется спать.",
            "Я голоден/голодна.",
            "Я хочу пить.",
            "Я нервничаю.",
            "Я волнуюсь.",
            "Я злюсь.",
            "Я удивлён/удивлена.",
            "Мне страшно.",
            "Мне скучно.",
            "Мне одиноко.",
            "Я в стрессе.",
            "Всё хорошо.",
            "Мне плохо.",
            "Мне нравится.",
            "Мне не нравится.",
            "Я скучаю по тебе.",
            "Я спокоен/спокойна.",
        ],
    },

    // --- Chinese (Simplified) ---
    zh: {
        greeting: [
            "你好。",
            "早上好。",
            "晚上好。",
            "很高兴认识你。",
            "好久不见。",
            "你好吗？",
            "我很好。",
            "谢谢。",
            "对不起。",
            "请。",
            "请再说一遍。",
            "请说慢一点。",
            "我明白了。",
            "我不明白。",
            "请帮帮我。",
            "你叫什么名字？",
            "我叫____。",
            "再见。",
            "保重。",
            "请多关照。",
        ],
        dining: [
            "请给我菜单。",
            "请给我水。",
            "我要这个。",
            "你推荐什么？",
            "这个辣吗？",
            "不要辣。",
            "请结账。",
            "可以刷卡吗？",
            "请给我小票。",
            "可以打包吗？",
            "很好吃。",
            "我吃饱了。",
            "我是素食者。",
            "我有过敏。",
            "不要肉。",
            "不要洋葱。",
            "再来一个。",
            "我有预订。",
            "我们两位。",
            "干杯。",
        ],
        travel: [
            "洗手间在哪里？",
            "车站在哪里？",
            "怎么去这里？",
            "我迷路了。",
            "请在地图上给我看。",
            "要多久？",
            "请给我一张票。",
            "请给我两张票。",
            "现在几点？",
            "几点出发？",
            "请帮我叫出租车。",
            "请在这里停。",
            "酒店在哪里？",
            "入口在哪里？",
            "出口在哪里？",
            "请直走。",
            "请左转。",
            "请右转。",
            "请帮我拍照。",
            "多少钱？",
        ],
        emotions: [
            "我很开心。",
            "我很难过。",
            "我累了。",
            "我困了。",
            "我饿了。",
            "我渴了。",
            "我紧张。",
            "我担心。",
            "我生气。",
            "我吓了一跳。",
            "我害怕。",
            "我无聊。",
            "我很孤单。",
            "我有压力。",
            "没事。",
            "我不太好。",
            "我喜欢。",
            "我不喜欢。",
            "我想你。",
            "我很冷静。",
        ],
    },

    // --- Arabic (Modern Standard, beginner-friendly; gender variants via slash) ---
    ar: {
        greeting: [
            "مرحبًا.",
            "صباح الخير.",
            "مساء الخير.",
            "تشرفتُ بلقائك.",
            "اشتقتُ إليك.",
            "كيف حالك؟",
            "أنا بخير.",
            "شكرًا.",
            "آسف/آسفة.",
            "من فضلك.",
            "هل يمكنك أن تكرر؟",
            "تحدث ببطء من فضلك.",
            "أنا أفهم.",
            "أنا لا أفهم.",
            "ساعدني من فضلك.",
            "ما اسمك؟",
            "أنا ____.",
            "إلى اللقاء.",
            "اعتنِ بنفسك.",
            "سعيد/سعيدة بلقائك.",
        ],
        dining: [
            "القائمة من فضلك.",
            "ماء من فضلك.",
            "هذا من فضلك.",
            "ماذا توصي؟",
            "هل هذا حار؟",
            "بدون حار من فضلك.",
            "الحساب من فضلك.",
            "هل يمكنني الدفع بالبطاقة؟",
            "الإيصال من فضلك.",
            "للأخذ من فضلك.",
            "لذيذ جدًا.",
            "أنا شبعان/شبعانة.",
            "أنا نباتي/نباتية.",
            "لدي حساسية.",
            "بدون لحم من فضلك.",
            "بدون بصل من فضلك.",
            "واحد آخر من فضلك.",
            "لدي حجز.",
            "نحن اثنان.",
            "في صحتك.",
        ],
        travel: [
            "أين الحمّام؟",
            "أين المحطة؟",
            "كيف أصل إلى هنا؟",
            "أنا تائه/تائهة.",
            "أرني على الخريطة من فضلك.",
            "كم يستغرق؟",
            "تذكرة من فضلك.",
            "تذكرتان من فضلك.",
            "كم الساعة؟",
            "متى يغادر؟",
            "اتصل بسيارة أجرة من فضلك.",
            "توقف هنا من فضلك.",
            "أين الفندق؟",
            "أين المدخل؟",
            "أين المخرج؟",
            "اذهب مستقيمًا من فضلك.",
            "انعطف يسارًا من فضلك.",
            "انعطف يمينًا من فضلك.",
            "التقط صورة من فضلك.",
            "بكم هذا؟",
        ],
        emotions: [
            "أنا سعيد/سعيدة.",
            "أنا حزين/حزينة.",
            "أنا متعب/متعبة.",
            "أنا نعسان/نعسانة.",
            "أنا جائع/جائعة.",
            "أنا عطشان/عطشانة.",
            "أنا متوتر/متوترة.",
            "أنا قلق/قلقة.",
            "أنا غاضب/غاضبة.",
            "أنا مصدوم/مصدومة.",
            "أنا خائف/خائفة.",
            "أنا أشعر بالملل.",
            "أنا وحيد/وحيدة.",
            "أنا تحت ضغط.",
            "أنا بخير.",
            "أنا لست بخير.",
            "أنا أحب هذا.",
            "أنا لا أحب هذا.",
            "أشتاق إليك.",
            "أنا هادئ/هادئة.",
        ],
    },

    // --- Hindi ---
    hi: {
        greeting: [
            "नमस्ते।",
            "सुप्रभात।",
            "शुभ संध्या।",
            "आपसे मिलकर खुशी हुई।",
            "बहुत दिनों बाद मिले।",
            "आप कैसे हैं?",
            "मैं ठीक हूँ।",
            "धन्यवाद।",
            "माफ़ कीजिए।",
            "कृपया।",
            "फिर से कहिए।",
            "धीरे बोलिए।",
            "मैं समझ गया/गई।",
            "मैं नहीं समझा/समझी।",
            "कृपया मदद करें।",
            "आपका नाम क्या है?",
            "मैं ____ हूँ।",
            "फिर मिलेंगे।",
            "अपना ख्याल रखिए।",
            "आपसे मिलकर अच्छा लगा।",
        ],
        dining: [
            "मेन्यू दीजिए।",
            "पानी दीजिए।",
            "यह दीजिए।",
            "आप क्या सुझाएंगे?",
            "क्या यह तीखा है?",
            "कम तीखा कीजिए।",
            "बिल दीजिए।",
            "क्या कार्ड चलेगा?",
            "रसीद दीजिए।",
            "पैक कर दीजिए।",
            "बहुत स्वादिष्ट है।",
            "मेरा पेट भर गया।",
            "मैं शाकाहारी हूँ।",
            "मुझे एलर्जी है।",
            "बिना मांस के।",
            "बिना प्याज़ के।",
            "एक और दीजिए।",
            "मेरी बुकिंग है।",
            "हम दो हैं।",
            "चीयर्स।",
        ],
        travel: [
            "शौचालय कहाँ है?",
            "स्टेशन कहाँ है?",
            "मैं यहाँ कैसे जाऊँ?",
            "मैं रास्ता भूल गया/गई।",
            "नक्शे पर दिखाइए।",
            "कितना समय लगेगा?",
            "एक टिकट दीजिए।",
            "दो टिकट दीजिए।",
            "अभी कितने बजे हैं?",
            "यह कब निकलता है?",
            "टैक्सी बुलाइए।",
            "यहाँ रोकिए।",
            "होटल कहाँ है?",
            "प्रवेश कहाँ है?",
            "निकास कहाँ है?",
            "सीधे जाइए।",
            "बाएँ मुड़िए।",
            "दाएँ मुड़िए।",
            "फोटो खींचिए।",
            "यह कितने का है?",
        ],
        emotions: [
            "मैं खुश हूँ।",
            "मैं उदास हूँ।",
            "मैं थक गया/गई हूँ।",
            "मुझे नींद आ रही है।",
            "मुझे भूख लगी है।",
            "मुझे प्यास लगी है।",
            "मैं घबराया/घबराई हूँ।",
            "मैं चिंतित हूँ।",
            "मैं गुस्से में हूँ।",
            "मुझे आश्चर्य हुआ।",
            "मुझे डर लग रहा है।",
            "मुझे बोर लग रहा है।",
            "मुझे अकेलापन लग रहा है।",
            "मुझे तनाव है।",
            "मैं ठीक हूँ।",
            "मैं ठीक नहीं हूँ।",
            "मुझे यह पसंद है।",
            "मुझे यह पसंद नहीं है।",
            "मुझे आपकी याद आती है।",
            "मैं शांत हूँ।",
        ],
    },

    // --- Thai (ครับ/ค่ะ) ---
    th: {
        greeting: [
            "สวัสดีครับ/ค่ะ",
            "สวัสดีตอนเช้าครับ/ค่ะ",
            "สวัสดีตอนเย็นครับ/ค่ะ",
            "ยินดีที่ได้รู้จักครับ/ค่ะ",
            "ไม่เจอกันนานครับ/ค่ะ",
            "สบายดีไหมครับ/ค่ะ",
            "สบายดีครับ/ค่ะ",
            "ขอบคุณครับ/ค่ะ",
            "ขอโทษครับ/ค่ะ",
            "กรุณาครับ/ค่ะ",
            "พูดอีกครั้งได้ไหมครับ/ค่ะ",
            "พูดช้า ๆ หน่อยครับ/ค่ะ",
            "เข้าใจครับ/ค่ะ",
            "ไม่เข้าใจครับ/ค่ะ",
            "ช่วยด้วยครับ/ค่ะ",
            "คุณชื่ออะไรครับ/ค่ะ",
            "ฉันชื่อ ____ ครับ/ค่ะ",
            "แล้วเจอกันครับ/ค่ะ",
            "ดูแลตัวเองด้วยครับ/ค่ะ",
            "ฝากตัวด้วยครับ/ค่ะ",
        ],
        dining: [
            "ขอเมนูหน่อยครับ/ค่ะ",
            "ขอน้ำหน่อยครับ/ค่ะ",
            "เอาอันนี้ครับ/ค่ะ",
            "แนะนำอะไรดีครับ/ค่ะ",
            "อันนี้เผ็ดไหมครับ/ค่ะ",
            "ไม่เผ็ดครับ/ค่ะ",
            "คิดเงินด้วยครับ/ค่ะ",
            "จ่ายบัตรได้ไหมครับ/ค่ะ",
            "ขอใบเสร็จด้วยครับ/ค่ะ",
            "ใส่ห่อได้ไหมครับ/ค่ะ",
            "อร่อยมากครับ/ค่ะ",
            "อิ่มแล้วครับ/ค่ะ",
            "ฉันเป็นมังสวิรัติครับ/ค่ะ",
            "ฉันแพ้อาหารครับ/ค่ะ",
            "ไม่ใส่เนื้อครับ/ค่ะ",
            "ไม่ใส่หอมครับ/ค่ะ",
            "ขออีกหนึ่งครับ/ค่ะ",
            "ฉันจองไว้ครับ/ค่ะ",
            "สองคนครับ/ค่ะ",
            "ชนแก้วครับ/ค่ะ",
        ],
        travel: [
            "ห้องน้ำอยู่ที่ไหนครับ/ค่ะ",
            "สถานีอยู่ที่ไหนครับ/ค่ะ",
            "ไปที่นี่อย่างไรครับ/ค่ะ",
            "ฉันหลงทางครับ/ค่ะ",
            "ช่วยชี้ในแผนที่ได้ไหมครับ/ค่ะ",
            "ใช้เวลานานแค่ไหนครับ/ค่ะ",
            "ขอตั๋วหนึ่งใบครับ/ค่ะ",
            "ขอตั๋วสองใบครับ/ค่ะ",
            "ตอนนี้กี่โมงครับ/ค่ะ",
            "ออกกี่โมงครับ/ค่ะ",
            "เรียกแท็กซี่ให้หน่อยครับ/ค่ะ",
            "จอดตรงนี้ครับ/ค่ะ",
            "โรงแรมอยู่ที่ไหนครับ/ค่ะ",
            "ทางเข้าอยู่ที่ไหนครับ/ค่ะ",
            "ทางออกอยู่ที่ไหนครับ/ค่ะ",
            "ตรงไปครับ/ค่ะ",
            "เลี้ยวซ้ายครับ/ค่ะ",
            "เลี้ยวขวาครับ/ค่ะ",
            "ช่วยถ่ายรูปให้หน่อยครับ/ค่ะ",
            "ราคาเท่าไหร่ครับ/ค่ะ",
        ],
        emotions: [
            "ฉันมีความสุขครับ/ค่ะ",
            "ฉันเศร้าครับ/ค่ะ",
            "ฉันเหนื่อยครับ/ค่ะ",
            "ฉันง่วงครับ/ค่ะ",
            "ฉันหิวครับ/ค่ะ",
            "ฉันกระหายน้ำครับ/ค่ะ",
            "ฉันตื่นเต้น/กังวลครับ/ค่ะ",
            "ฉันกังวลครับ/ค่ะ",
            "ฉันโกรธครับ/ค่ะ",
            "ฉันตกใจครับ/ค่ะ",
            "ฉันกลัวครับ/ค่ะ",
            "ฉันเบื่อครับ/ค่ะ",
            "ฉันเหงาครับ/ค่ะ",
            "ฉันเครียดครับ/ค่ะ",
            "ฉันโอเคครับ/ค่ะ",
            "ฉันไม่โอเคครับ/ค่ะ",
            "ฉันชอบครับ/ค่ะ",
            "ฉันไม่ชอบครับ/ค่ะ",
            "ฉันคิดถึงคุณครับ/ค่ะ",
            "ฉันใจเย็นครับ/ค่ะ",
        ],
    },

    // --- Vietnamese ---
    vi: {
        greeting: [
            "Xin chào.",
            "Chào buổi sáng.",
            "Chào buổi tối.",
            "Rất vui được gặp bạn.",
            "Lâu rồi không gặp.",
            "Bạn khỏe không?",
            "Tôi khỏe.",
            "Cảm ơn.",
            "Xin lỗi.",
            "Làm ơn.",
            "Nói lại được không?",
            "Nói chậm lại, làm ơn.",
            "Tôi hiểu.",
            "Tôi không hiểu.",
            "Giúp tôi với.",
            "Bạn tên là gì?",
            "Tôi là ____.",
            "Hẹn gặp lại.",
            "Giữ gìn sức khỏe.",
            "Rất vui được gặp bạn.",
        ],
        dining: [
            "Cho tôi xem thực đơn.",
            "Cho tôi nước.",
            "Cho tôi cái này.",
            "Bạn gợi ý món nào?",
            "Cái này cay không?",
            "Không cay, làm ơn.",
            "Tính tiền, làm ơn.",
            "Tôi trả bằng thẻ được không?",
            "Cho tôi hóa đơn.",
            "Mang đi được không?",
            "Ngon quá.",
            "Tôi no rồi.",
            "Tôi ăn chay.",
            "Tôi bị dị ứng.",
            "Không thịt, làm ơn.",
            "Không hành, làm ơn.",
            "Cho tôi thêm một cái.",
            "Tôi có đặt chỗ.",
            "Hai người.",
            "Chúc mừng.",
        ],
        travel: [
            "Nhà vệ sinh ở đâu?",
            "Ga ở đâu?",
            "Đi đến đây như thế nào?",
            "Tôi bị lạc.",
            "Chỉ trên bản đồ được không?",
            "Mất bao lâu?",
            "Cho tôi một vé.",
            "Cho tôi hai vé.",
            "Bây giờ mấy giờ?",
            "Mấy giờ khởi hành?",
            "Gọi taxi giúp tôi.",
            "Dừng ở đây, làm ơn.",
            "Khách sạn ở đâu?",
            "Lối vào ở đâu?",
            "Lối ra ở đâu?",
            "Đi thẳng.",
            "Rẽ trái.",
            "Rẽ phải.",
            "Chụp ảnh giúp tôi.",
            "Bao nhiêu tiền?",
        ],
        emotions: [
            "Tôi vui.",
            "Tôi buồn.",
            "Tôi mệt.",
            "Tôi buồn ngủ.",
            "Tôi đói.",
            "Tôi khát.",
            "Tôi lo lắng.",
            "Tôi lo.",
            "Tôi tức giận.",
            "Tôi bất ngờ.",
            "Tôi sợ.",
            "Tôi chán.",
            "Tôi cô đơn.",
            "Tôi căng thẳng.",
            "Tôi ổn.",
            "Tôi không ổn.",
            "Tôi thích.",
            "Tôi không thích.",
            "Tôi nhớ bạn.",
            "Tôi bình tĩnh.",
        ],
    },

    // --- Indonesian ---
    id: {
        greeting: [
            "Halo.",
            "Selamat pagi.",
            "Selamat malam.",
            "Senang bertemu denganmu.",
            "Lama tidak bertemu.",
            "Apa kabar?",
            "Saya baik-baik saja.",
            "Terima kasih.",
            "Maaf.",
            "Tolong.",
            "Bisa ulangi?",
            "Bicara pelan-pelan, ya.",
            "Saya mengerti.",
            "Saya tidak mengerti.",
            "Tolong bantu saya.",
            "Siapa namamu?",
            "Saya ____.",
            "Sampai jumpa.",
            "Hati-hati.",
            "Senang bertemu denganmu.",
        ],
        dining: [
            "Menu, ya.",
            "Air putih, ya.",
            "Yang ini, ya.",
            "Rekomendasinya apa?",
            "Ini pedas?",
            "Jangan pedas, ya.",
            "Minta bill, ya.",
            "Bisa bayar pakai kartu?",
            "Minta struk, ya.",
            "Bisa dibungkus?",
            "Enak sekali.",
            "Saya kenyang.",
            "Saya vegetarian.",
            "Saya punya alergi.",
            "Tanpa daging, ya.",
            "Tanpa bawang, ya.",
            "Tambah satu lagi, ya.",
            "Saya punya reservasi.",
            "Untuk dua orang.",
            "Bersulang.",
        ],
        travel: [
            "Di mana toilet?",
            "Di mana stasiun?",
            "Bagaimana cara ke sini?",
            "Saya tersesat.",
            "Tunjukkan di peta, ya.",
            "Berapa lama?",
            "Satu tiket, ya.",
            "Dua tiket, ya.",
            "Jam berapa sekarang?",
            "Berangkat jam berapa?",
            "Tolong panggil taksi.",
            "Berhenti di sini, ya.",
            "Di mana hotel?",
            "Di mana pintu masuk?",
            "Di mana pintu keluar?",
            "Lurus saja.",
            "Belok kiri.",
            "Belok kanan.",
            "Tolong foto saya.",
            "Berapa harganya?",
        ],
        emotions: [
            "Saya senang.",
            "Saya sedih.",
            "Saya capek.",
            "Saya mengantuk.",
            "Saya lapar.",
            "Saya haus.",
            "Saya gugup.",
            "Saya khawatir.",
            "Saya marah.",
            "Saya kaget.",
            "Saya takut.",
            "Saya bosan.",
            "Saya kesepian.",
            "Saya stres.",
            "Saya baik-baik saja.",
            "Saya tidak baik-baik saja.",
            "Saya suka.",
            "Saya tidak suka.",
            "Saya rindu kamu.",
            "Saya tenang.",
        ],
    },

    // --- Turkish ---
    tr: {
        greeting: [
            "Merhaba.",
            "Günaydın.",
            "İyi akşamlar.",
            "Tanıştığıma memnun oldum.",
            "Uzun zaman oldu.",
            "Nasılsın?",
            "İyiyim.",
            "Teşekkürler.",
            "Özür dilerim.",
            "Lütfen.",
            "Tekrar eder misin?",
            "Yavaş konuşur musun?",
            "Anlıyorum.",
            "Anlamıyorum.",
            "Yardım eder misin?",
            "Adın ne?",
            "Ben ____.",
            "Görüşürüz.",
            "Kendine dikkat et.",
            "Memnun oldum.",
        ],
        dining: [
            "Menü lütfen.",
            "Su lütfen.",
            "Bunu lütfen.",
            "Ne önerirsin?",
            "Bu acı mı?",
            "Acısız lütfen.",
            "Hesap lütfen.",
            "Kartla ödeyebilir miyim?",
            "Fiş lütfen.",
            "Paket olabilir mi?",
            "Çok lezzetli.",
            "Doydum.",
            "Ben vejetaryenim.",
            "Alerjim var.",
            "Etsiz lütfen.",
            "Soğansız lütfen.",
            "Bir tane daha lütfen.",
            "Rezervasyonum var.",
            "İki kişiyiz.",
            "Şerefe.",
        ],
        travel: [
            "Tuvalet nerede?",
            "İstasyon nerede?",
            "Buraya nasıl giderim?",
            "Kayboldum.",
            "Haritada gösterebilir misin?",
            "Ne kadar sürer?",
            "Bir bilet lütfen.",
            "İki bilet lütfen.",
            "Saat kaç?",
            "Kaçta kalkıyor?",
            "Taksi çağırır mısınız?",
            "Burada dur lütfen.",
            "Otel nerede?",
            "Giriş nerede?",
            "Çıkış nerede?",
            "Dümdüz gidin.",
            "Sola dönün.",
            "Sağa dönün.",
            "Fotoğraf çeker misin?",
            "Ne kadar?",
        ],
        emotions: [
            "Mutluyum.",
            "Üzgünüm.",
            "Yorgunum.",
            "Uykum var.",
            "Acıktım.",
            "Susadım.",
            "Gerginim.",
            "Endişeliyim.",
            "Kızgınım.",
            "Şaşırdım.",
            "Korkuyorum.",
            "Sıkıldım.",
            "Yalnızım.",
            "Stresliyim.",
            "İyiyim.",
            "İyi değilim.",
            "Hoşuma gidiyor.",
            "Hoşuma gitmiyor.",
            "Seni özledim.",
            "Sakinim.",
        ],
    },

    // --- Dutch ---
    nl: {
        greeting: [
            "Hallo.",
            "Goedemorgen.",
            "Goedenavond.",
            "Leuk je te ontmoeten.",
            "Lang niet gezien.",
            "Hoe gaat het?",
            "Het gaat goed.",
            "Dank je.",
            "Sorry.",
            "Alsjeblieft.",
            "Kun je dat herhalen?",
            "Spreek langzamer, alsjeblieft.",
            "Ik begrijp het.",
            "Ik begrijp het niet.",
            "Help me, alsjeblieft.",
            "Hoe heet je?",
            "Ik ben ____.",
            "Tot ziens.",
            "Pas goed op jezelf.",
            "Aangenaam.",
        ],
        dining: [
            "De menukaart, alstublieft.",
            "Water, alstublieft.",
            "Deze, alstublieft.",
            "Wat raadt u aan?",
            "Is dit pittig?",
            "Niet pittig, alstublieft.",
            "De rekening, alstublieft.",
            "Kan ik met kaart betalen?",
            "De bon, alstublieft.",
            "Om mee te nemen, alstublieft.",
            "Het is lekker.",
            "Ik zit vol.",
            "Ik ben vegetariër.",
            "Ik heb een allergie.",
            "Zonder vlees, alstublieft.",
            "Zonder ui, alstublieft.",
            "Nog één, alstublieft.",
            "Ik heb een reservering.",
            "We zijn met z’n tweeën.",
            "Proost.",
        ],
        travel: [
            "Waar is het toilet?",
            "Waar is het station?",
            "Hoe kom ik hier?",
            "Ik ben verdwaald.",
            "Kunt u het op de kaart laten zien?",
            "Hoe lang duurt het?",
            "Een kaartje, alstublieft.",
            "Twee kaartjes, alstublieft.",
            "Hoe laat is het?",
            "Hoe laat vertrekt het?",
            "Kunt u een taxi bellen?",
            "Kunt u hier stoppen?",
            "Waar is het hotel?",
            "Waar is de ingang?",
            "Waar is de uitgang?",
            "Ga rechtdoor.",
            "Sla linksaf.",
            "Sla rechtsaf.",
            "Kunt u een foto maken?",
            "Hoeveel kost het?",
        ],
        emotions: [
            "Ik ben blij.",
            "Ik ben verdrietig.",
            "Ik ben moe.",
            "Ik ben slaperig.",
            "Ik heb honger.",
            "Ik heb dorst.",
            "Ik ben zenuwachtig.",
            "Ik maak me zorgen.",
            "Ik ben boos.",
            "Ik ben verrast.",
            "Ik ben bang.",
            "Ik verveel me.",
            "Ik voel me eenzaam.",
            "Ik ben gestrest.",
            "Het gaat wel.",
            "Het gaat niet goed.",
            "Ik vind het leuk.",
            "Ik vind het niet leuk.",
            "Ik mis je.",
            "Ik ben rustig.",
        ],
    },

    // --- Swedish ---
    sv: {
        greeting: [
            "Hej.",
            "God morgon.",
            "God kväll.",
            "Trevligt att träffas.",
            "Det var länge sen.",
            "Hur mår du?",
            "Jag mår bra.",
            "Tack.",
            "Förlåt.",
            "Snälla.",
            "Kan du säga det igen?",
            "Prata långsammare, snälla.",
            "Jag förstår.",
            "Jag förstår inte.",
            "Hjälp mig, snälla.",
            "Vad heter du?",
            "Jag heter ____.",
            "Vi ses.",
            "Ta hand om dig.",
            "Trevligt att träffas.",
        ],
        dining: [
            "Menyn, tack.",
            "Vatten, tack.",
            "Den här, tack.",
            "Vad rekommenderar du?",
            "Är det här starkt?",
            "Inte starkt, tack.",
            "Notan, tack.",
            "Kan jag betala med kort?",
            "Kvittot, tack.",
            "För avhämtning, tack.",
            "Det är gott.",
            "Jag är mätt.",
            "Jag är vegetarian.",
            "Jag har en allergi.",
            "Utan kött, tack.",
            "Utan lök, tack.",
            "En till, tack.",
            "Jag har en bokning.",
            "Vi är två.",
            "Skål.",
        ],
        travel: [
            "Var är toaletten?",
            "Var är stationen?",
            "Hur kommer jag hit?",
            "Jag har gått vilse.",
            "Visa på kartan, snälla.",
            "Hur lång tid tar det?",
            "En biljett, tack.",
            "Två biljetter, tack.",
            "Vad är klockan?",
            "När går den?",
            "Kan du ringa en taxi?",
            "Stanna här, tack.",
            "Var är hotellet?",
            "Var är ingången?",
            "Var är utgången?",
            "Gå rakt fram.",
            "Sväng vänster.",
            "Sväng höger.",
            "Kan du ta en bild?",
            "Hur mycket kostar det?",
        ],
        emotions: [
            "Jag är glad.",
            "Jag är ledsen.",
            "Jag är trött.",
            "Jag är sömnig.",
            "Jag är hungrig.",
            "Jag är törstig.",
            "Jag är nervös.",
            "Jag är orolig.",
            "Jag är arg.",
            "Jag är förvånad.",
            "Jag är rädd.",
            "Jag har tråkigt.",
            "Jag känner mig ensam.",
            "Jag är stressad.",
            "Jag mår bra.",
            "Jag mår inte bra.",
            "Jag gillar det.",
            "Jag gillar det inte.",
            "Jag saknar dig.",
            "Jag är lugn.",
        ],
    },

    // --- Polish ---
    pl: {
        greeting: [
            "Cześć.",
            "Dzień dobry.",
            "Dobry wieczór.",
            "Miło mi.",
            "Dawno się nie widzieliśmy.",
            "Jak się masz?",
            "Mam się dobrze.",
            "Dziękuję.",
            "Przepraszam.",
            "Proszę.",
            "Możesz powtórzyć?",
            "Mów wolniej, proszę.",
            "Rozumiem.",
            "Nie rozumiem.",
            "Pomóż mi, proszę.",
            "Jak masz na imię?",
            "Jestem ____.",
            "Do zobaczenia.",
            "Trzymaj się.",
            "Miło mi cię poznać.",
        ],
        dining: [
            "Poproszę menu.",
            "Poproszę wodę.",
            "Poproszę to.",
            "Co polecasz?",
            "Czy to jest ostre?",
            "Nieostre, proszę.",
            "Poproszę rachunek.",
            "Czy mogę zapłacić kartą?",
            "Poproszę paragon.",
            "Na wynos, proszę.",
            "To jest pyszne.",
            "Jestem najedzony/najedzona.",
            "Jestem wegetarianinem/wegetarianką.",
            "Mam alergię.",
            "Bez mięsa, proszę.",
            "Bez cebuli, proszę.",
            "Jeszcze jedno, proszę.",
            "Mam rezerwację.",
            "Jesteśmy we dwoje.",
            "Na zdrowie.",
        ],
        travel: [
            "Gdzie jest toaleta?",
            "Gdzie jest stacja?",
            "Jak dojadę tutaj?",
            "Zgubiłem się/zgubiłam się.",
            "Pokaż na mapie, proszę.",
            "Ile to trwa?",
            "Jeden bilet, proszę.",
            "Dwa bilety, proszę.",
            "Która jest godzina?",
            "O której odjeżdża?",
            "Proszę wezwać taksówkę.",
            "Proszę zatrzymać się tutaj.",
            "Gdzie jest hotel?",
            "Gdzie jest wejście?",
            "Gdzie jest wyjście?",
            "Prosto, proszę.",
            "W lewo, proszę.",
            "W prawo, proszę.",
            "Zrób mi zdjęcie, proszę.",
            "Ile to kosztuje?",
        ],
        emotions: [
            "Jestem szczęśliwy/szczęśliwa.",
            "Jestem smutny/smutna.",
            "Jestem zmęczony/zmęczona.",
            "Jestem senny/senna.",
            "Jestem głodny/głodna.",
            "Chce mi się pić.",
            "Jestem zdenerwowany/zdenerwowana.",
            "Martwię się.",
            "Jestem zły/zła.",
            "Jestem zaskoczony/zaskoczona.",
            "Boję się.",
            "Nudzę się.",
            "Czuję się samotny/samotna.",
            "Jestem zestresowany/zestresowana.",
            "W porządku.",
            "Nie jest dobrze.",
            "Podoba mi się.",
            "Nie podoba mi się.",
            "Tęsknię za tobą.",
            "Jestem spokojny/spokojna.",
        ],
    },
};

function pad2(n: number) {
    return String(n).padStart(2, "0");
}

function buildPhrases(): Record<string, Phrase[]> {
    const out: Record<string, Phrase[]> = {};
    for (const lang of Object.keys(TARGET)) {
        const phrases: Phrase[] = [];
        for (const cat of Object.keys(JP)) {
            const jpList = JP[cat];
            const tgtList = TARGET[lang]?.[cat];
            if (!tgtList || tgtList.length !== 20) {
                throw new Error(`TARGET missing/invalid: lang=${lang}, category=${cat}`);
            }
            for (let i = 0; i < 20; i++) {
                phrases.push({
                    id: `${lang}-${cat}-${pad2(i + 1)}`,
                    categoryId: cat,
                    targetText: tgtList[i],
                    translation: jpList[i],
                });
            }
        }
        out[lang] = phrases;
    }
    return out;
}

export const PHRASES: Record<string, Phrase[]> = buildPhrases();

// Mock corpus for exploration - simple flat list
// (Here: 12 examples per language, picked from the phrase lists: 3 per category)
const CORPUS: Record<string, { text: string; translation: string }[]> = (() => {
    const out: Record<string, { text: string; translation: string }[]> = {};
    for (const lang of Object.keys(PHRASES)) {
        const list = PHRASES[lang];
        const pick: { text: string; translation: string }[] = [];
        const byCat: Record<string, Phrase[]> = {};
        for (const p of list) {
            byCat[p.categoryId] ||= [];
            byCat[p.categoryId].push(p);
        }
        for (const cat of ["greeting", "dining", "travel", "emotions"]) {
            const arr = byCat[cat] || [];
            pick.push(
                { text: arr[0]?.targetText ?? "", translation: arr[0]?.translation ?? "" },
                { text: arr[1]?.targetText ?? "", translation: arr[1]?.translation ?? "" },
                { text: arr[2]?.targetText ?? "", translation: arr[2]?.translation ?? "" }
            );
        }
        out[lang] = pick.filter(x => x.text && x.translation);
    }
    return out;
})();

export const searchExamples = async (
    lang: string,
    query: string
): Promise<{ id: string; text: string; translation: string }[]> => {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 600));

    const corpus = CORPUS[lang] || [];
    const normalizedQuery = query.toLowerCase().trim();

    return corpus
        .filter(item => item.text.toLowerCase().includes(normalizedQuery))
        .map((item, index) => ({ id: `ex-${index}`, ...item }));
};
