-- Seed common English word parts (prefixes, suffixes, roots)
-- Each entry includes: part, type, meaning (Japanese), origin language, example words, learning hint

INSERT INTO etymology_word_parts (part, part_type, meaning, origin_language, examples, learning_hint) VALUES
-- ===== PREFIXES =====
('un-', 'prefix', '否定・反対', 'old_english', ARRAY['undo', 'unhappy', 'unknown', 'unfair', 'unlikely'], 'un-は最も一般的な否定接頭辞。形容詞・動詞に付けて反対の意味にする'),
('re-', 'prefix', '再び・後ろに', 'latin', ARRAY['return', 'review', 'rebuild', 'repeat', 'restore'], 're-を見たら「もう一度」と覚えよう。英語で最も頻出する接頭辞の一つ'),
('pre-', 'prefix', '前に・あらかじめ', 'latin', ARRAY['predict', 'prevent', 'prepare', 'preview', 'precede'], 'pre-は「前もって」。preview=前もって見る、predict=前もって言う'),
('dis-', 'prefix', '否定・離れて', 'latin', ARRAY['discover', 'disagree', 'disappear', 'discount', 'disconnect'], 'dis-は「離れる・反対」。un-と似ているがラテン語系の単語に付く'),
('mis-', 'prefix', '誤って・悪く', 'old_english', ARRAY['mistake', 'misunderstand', 'mislead', 'misuse', 'misbehave'], 'mis-は「間違い」。mistake=間違って取る、misunderstand=間違って理解する'),
('over-', 'prefix', '過度に・上に', 'old_english', ARRAY['overcome', 'overlook', 'overflow', 'overwork', 'overseas'], 'over-は「やりすぎ」または「上から」の2つの意味を持つ'),
('under-', 'prefix', '下に・不足', 'old_english', ARRAY['understand', 'underestimate', 'underground', 'undertake', 'underline'], 'under-は「下」と「不十分」。underestimate=過小評価する'),
('out-', 'prefix', '外に・超えて', 'old_english', ARRAY['outcome', 'outline', 'output', 'outperform', 'outstanding'], 'out-は「外へ」または「〜より優れる」。outperform=上回る'),
('sub-', 'prefix', '下に・副', 'latin', ARRAY['subway', 'submarine', 'subject', 'submit', 'subscribe'], 'sub-は「下」。subway=地下鉄、submarine=海面下=潜水艦'),
('super-', 'prefix', '上に・超えて', 'latin', ARRAY['supermarket', 'superman', 'supernatural', 'supervise', 'superior'], 'super-はsub-の反対で「上・超」。supervise=上から見る=監督する'),
('inter-', 'prefix', '間に・相互に', 'latin', ARRAY['international', 'internet', 'interview', 'interact', 'interrupt'], 'inter-は「間」。international=国と国の間=国際的'),
('trans-', 'prefix', '横切って・越えて', 'latin', ARRAY['transport', 'translate', 'transfer', 'transform', 'transparent'], 'trans-は「向こう側へ」。transport=向こうへ運ぶ、translate=言語を越える'),
('anti-', 'prefix', '反対・対抗', 'greek', ARRAY['antibiotic', 'antisocial', 'antivirus', 'antonym', 'antifreeze'], 'anti-は「反対」。antibiotic=生命(bio)に反する=抗生物質'),
('auto-', 'prefix', '自己・自動', 'greek', ARRAY['automatic', 'automobile', 'autobiography', 'autonomy', 'autopilot'], 'auto-は「自分で」。automobile=自分で動く=自動車'),
('bi-', 'prefix', '二つの', 'latin', ARRAY['bicycle', 'bilingual', 'binocular', 'binary', 'biweekly'], 'bi-は「2」。bicycle=2つの車輪、bilingual=2つの言語'),
('co-', 'prefix', '共に', 'latin', ARRAY['cooperate', 'coexist', 'coworker', 'coordinate', 'coauthor'], 'co-は「一緒に」。cooperate=一緒に働く=協力する'),
('de-', 'prefix', '離れて・下に・除去', 'latin', ARRAY['decrease', 'depart', 'destroy', 'decode', 'deforest'], 'de-は「取り除く・下げる」。decode=コードを解く、deforest=森林を除去'),
('ex-', 'prefix', '外に・元〜', 'latin', ARRAY['exit', 'export', 'exclude', 'expose', 'ex-president'], 'ex-は「外へ」。export=外へ運ぶ=輸出、exit=外へ出る'),
('extra-', 'prefix', '外に・超えて', 'latin', ARRAY['extraordinary', 'extracurricular', 'extraterrestrial', 'extravagant'], 'extra-は「範囲の外」。extraordinary=通常(ordinary)の外=並外れた'),
('fore-', 'prefix', '前に・先に', 'old_english', ARRAY['forecast', 'foresee', 'forehead', 'foreground', 'foreword'], 'fore-はpre-のゲルマン語版で「前」。forecast=前もって計算する'),
('in-', 'prefix', '中に / 否定', 'latin', ARRAY['include', 'inside', 'invisible', 'incomplete', 'independent'], 'in-は「中に」と「否定」の2つの意味がある。文脈で判断'),
('micro-', 'prefix', '小さい', 'greek', ARRAY['microscope', 'microphone', 'microwave', 'microorganism', 'microchip'], 'micro-は「小さい」。microscope=小さいものを見る装置'),
('macro-', 'prefix', '大きい', 'greek', ARRAY['macroeconomics', 'macroscopic', 'macrocosm'], 'macro-はmicro-の反対で「大きい」。macroeconomics=大きな経済=マクロ経済'),
('mono-', 'prefix', '一つの', 'greek', ARRAY['monologue', 'monopoly', 'monotone', 'monorail', 'monarchy'], 'mono-は「1つ」。monologue=1人の言葉=独白、monopoly=1つの販売=独占'),
('multi-', 'prefix', '多くの', 'latin', ARRAY['multiply', 'multimedia', 'multilingual', 'multitask', 'multicolor'], 'multi-は「たくさん」。multilingual=多言語、multimedia=多メディア'),
('poly-', 'prefix', '多くの', 'greek', ARRAY['polygon', 'polyglot', 'polynomial', 'polysyllabic'], 'poly-はmulti-のギリシャ語版で「多い」。polyglot=多言語話者'),
('neo-', 'prefix', '新しい', 'greek', ARRAY['neonatal', 'neoclassical', 'neologism', 'neon'], 'neo-は「新しい」。neologism=新しい(neo)言葉(logos)=新語'),
('non-', 'prefix', '否定', 'latin', ARRAY['nonsense', 'nonfiction', 'nonprofit', 'nonverbal', 'nonexistent'], 'non-はシンプルに「〜でない」。un-より中立的な否定'),
('post-', 'prefix', '後に', 'latin', ARRAY['postpone', 'postwar', 'postscript', 'postmortem', 'postgraduate'], 'post-は「後」。pre-の反対。postpone=後に置く=延期する'),
('pro-', 'prefix', '前に・賛成', 'latin', ARRAY['progress', 'promote', 'produce', 'project', 'proactive'], 'pro-は「前へ」。progress=前へ進む、promote=前へ動かす=昇進させる'),
('semi-', 'prefix', '半分', 'latin', ARRAY['semicircle', 'semifinal', 'semiconductor', 'semiannual'], 'semi-は「半分」。semicircle=半円、semifinal=準決勝'),
('tele-', 'prefix', '遠くの', 'greek', ARRAY['telephone', 'television', 'telescope', 'telegram', 'teleport'], 'tele-は「遠い」。telephone=遠い声、television=遠い映像、telescope=遠くを見る'),
('tri-', 'prefix', '三つの', 'latin', ARRAY['triangle', 'trilogy', 'tricycle', 'triple', 'tripod'], 'tri-は「3」。triangle=3つの角、trilogy=3部作'),
('uni-', 'prefix', '一つの', 'latin', ARRAY['universe', 'uniform', 'unique', 'unite', 'unicorn'], 'uni-は「1つ」。universe=1つに回る=宇宙、uniform=1つの形=制服'),
('hyper-', 'prefix', '過度に・超えて', 'greek', ARRAY['hyperactive', 'hyperlink', 'hypertension', 'hyperbole'], 'hyper-は「超えすぎ」。hyperactive=過度に活動的'),
('hypo-', 'prefix', '下に・不足', 'greek', ARRAY['hypothesis', 'hypothermia', 'hypodermic', 'hypoglycemia'], 'hypo-はhyper-の反対で「下・不足」。hypothermia=体温が低すぎる'),
('para-', 'prefix', '横に・近くに・防ぐ', 'greek', ARRAY['parallel', 'paragraph', 'parachute', 'paramedic', 'paradox'], 'para-は「横・近く・守る」。parachute=落下(chute)を防ぐ'),
('syn-', 'prefix', '共に・同じ', 'greek', ARRAY['synonym', 'synthesis', 'symphony', 'synchronize', 'syndrome'], 'syn-は「一緒に」。synonym=同じ(syn)名前(onym)=同義語'),
('counter-', 'prefix', '反対に・対抗', 'latin', ARRAY['counterpart', 'counterattack', 'counterclockwise', 'counteract'], 'counter-は「反対」。counterattack=反撃、counteract=対抗する'),
('mid-', 'prefix', '中間の', 'old_english', ARRAY['midnight', 'midterm', 'midpoint', 'middleware', 'midway'], 'mid-は「真ん中」。midnight=夜の真ん中、midterm=学期の中間'),

-- ===== SUFFIXES =====
('-able', 'suffix', '〜できる', 'latin', ARRAY['comfortable', 'available', 'readable', 'remarkable', 'sustainable'], '-ableは「〜できる」。read+able=読める、comfort+able=快適な'),
('-tion', 'suffix', '行為・状態（名詞化）', 'latin', ARRAY['education', 'information', 'nation', 'action', 'creation'], '-tionは動詞を名詞にする最頻出接尾辞。educate→education'),
('-ness', 'suffix', '性質・状態（名詞化）', 'old_english', ARRAY['happiness', 'darkness', 'kindness', 'weakness', 'sadness'], '-nessは形容詞を名詞にする。happy→happiness、dark→darkness'),
('-ment', 'suffix', '行為・結果（名詞化）', 'latin', ARRAY['development', 'movement', 'agreement', 'environment', 'government'], '-mentは動詞を名詞にする。develop→development、agree→agreement'),
('-ful', 'suffix', '〜に満ちた', 'old_english', ARRAY['beautiful', 'careful', 'powerful', 'grateful', 'wonderful'], '-fulは「いっぱい」。beautiful=美しさに満ちた、careful=注意に満ちた'),
('-less', 'suffix', '〜がない', 'old_english', ARRAY['homeless', 'careless', 'endless', 'hopeless', 'wireless'], '-lessは-fulの反対で「ない」。careless=注意がない、homeless=家がない'),
('-ly', 'suffix', '〜のように（副詞化）', 'old_english', ARRAY['quickly', 'carefully', 'happily', 'honestly', 'naturally'], '-lyは形容詞を副詞にする最も一般的な方法。quick→quickly'),
('-er', 'suffix', '〜する人・もの', 'old_english', ARRAY['teacher', 'player', 'writer', 'computer', 'driver'], '-erは「〜する人/もの」。teach+er=教える人、compute+er=計算する機械'),
('-or', 'suffix', '〜する人・もの', 'latin', ARRAY['actor', 'doctor', 'editor', 'inventor', 'professor'], '-orは-erのラテン語版。ラテン語由来の動詞に付くことが多い'),
('-ous', 'suffix', '〜の性質を持つ', 'latin', ARRAY['dangerous', 'famous', 'nervous', 'curious', 'generous'], '-ousは「〜の性質がある」。danger+ous=危険な性質の'),
('-ive', 'suffix', '〜の傾向がある', 'latin', ARRAY['active', 'creative', 'effective', 'attractive', 'negative'], '-iveは「〜しがちな」。create→creative=創造的な'),
('-al', 'suffix', '〜に関する（形容詞化）', 'latin', ARRAY['national', 'natural', 'personal', 'musical', 'cultural'], '-alは名詞を形容詞にする。nation→national、nature→natural'),
('-ity', 'suffix', '性質・状態（名詞化）', 'latin', ARRAY['reality', 'quality', 'ability', 'university', 'electricity'], '-ityは形容詞を名詞にする。real→reality、able→ability'),
('-ize', 'suffix', '〜化する（動詞化）', 'greek', ARRAY['realize', 'organize', 'modernize', 'customize', 'maximize'], '-izeは名詞・形容詞を動詞にする。modern→modernize=近代化する'),
('-ist', 'suffix', '〜する人・主義者', 'greek', ARRAY['artist', 'scientist', 'tourist', 'pianist', 'specialist'], '-istは「〜を専門とする人」。art→artist、science→scientist'),
('-ism', 'suffix', '主義・状態', 'greek', ARRAY['capitalism', 'tourism', 'racism', 'optimism', 'journalism'], '-ismは「主義・体制」。capital→capitalism、tour→tourism'),
('-logy', 'suffix', '〜学・研究', 'greek', ARRAY['biology', 'psychology', 'technology', 'geology', 'archaeology'], '-logyは「学問」。bio+logy=生命の学問=生物学'),
('-graphy', 'suffix', '〜記述・書くこと', 'greek', ARRAY['photography', 'biography', 'geography', 'typography', 'calligraphy'], '-graphyは「書くこと」。photo+graphy=光で書く=写真術'),
('-ment', 'suffix', '行為・結果（名詞化）', 'latin', ARRAY['achievement', 'treatment', 'equipment', 'measurement'], '-mentは行為や結果を表す名詞を作る'),
('-ance', 'suffix', '性質・状態（名詞化）', 'latin', ARRAY['performance', 'appearance', 'importance', 'distance', 'tolerance'], '-ance/-enceは状態を表す名詞。perform→performance'),
('-ence', 'suffix', '性質・状態（名詞化）', 'latin', ARRAY['confidence', 'difference', 'experience', 'independence', 'science'], '-enceは-anceの変形。動詞の語尾によって使い分ける'),
('-ic', 'suffix', '〜の性質を持つ', 'greek', ARRAY['dramatic', 'electric', 'historic', 'organic', 'romantic'], '-icはギリシャ語系の形容詞接尾辞。drama→dramatic'),
('-ous', 'suffix', '〜に満ちた', 'latin', ARRAY['adventurous', 'ambitious', 'conscious', 'mysterious', 'religious'], '-ousは「〜に満ちた」。mystery→mysterious=神秘に満ちた'),
('-ward', 'suffix', '〜の方向へ', 'old_english', ARRAY['forward', 'backward', 'upward', 'toward', 'inward'], '-wardは「方向」。forward=前の方へ、backward=後ろの方へ'),

-- ===== ROOTS =====
('aud', 'root', '聞く', 'latin', ARRAY['audience', 'audio', 'auditorium', 'audition', 'audible'], 'aud=聞く。audience=聞く人々=聴衆、audio=音声、audible=聞こえる'),
('bene', 'root', '良い', 'latin', ARRAY['benefit', 'benevolent', 'beneficial', 'benediction', 'benign'], 'bene=良い。benefit=良い結果、benevolent=良い意志=慈悲深い'),
('mal', 'root', '悪い', 'latin', ARRAY['malice', 'malfunction', 'malware', 'malicious', 'malnourished'], 'mal=悪い。beneの反対。malfunction=悪い機能=故障、malware=悪いソフト'),
('chrono', 'root', '時間', 'greek', ARRAY['chronological', 'chronicle', 'chronic', 'synchronize', 'anachronism'], 'chrono=時間。chronological=時間順の、chronic=長時間の=慢性的な'),
('dict', 'root', '言う', 'latin', ARRAY['dictionary', 'predict', 'contradict', 'dictate', 'verdict'], 'dict=言う。dictionary=言葉の本、predict=前もって言う=予言する'),
('duc', 'root', '導く', 'latin', ARRAY['produce', 'reduce', 'conduct', 'educate', 'introduce'], 'duc/duct=導く。produce=前に導く=生産する、educate=外に導く=教育する'),
('graph', 'root', '書く', 'greek', ARRAY['photograph', 'paragraph', 'biography', 'autograph', 'telegraph'], 'graph=書く。photograph=光で書く=写真、autograph=自分で書く=サイン'),
('mort', 'root', '死', 'latin', ARRAY['mortal', 'immortal', 'mortgage', 'mortuary', 'mortify'], 'mort=死。mortal=死ぬ運命の、immortal=不死の、mortgage=死の誓い(完済まで)'),
('path', 'root', '感じる・苦しむ', 'greek', ARRAY['sympathy', 'empathy', 'apathy', 'pathology', 'pathetic'], 'path=感情。sympathy=共に感じる=同情、apathy=感じない=無関心'),
('phon', 'root', '声・音', 'greek', ARRAY['telephone', 'microphone', 'phonetic', 'symphony', 'cacophony'], 'phon=音。telephone=遠い音、microphone=小さい音を大きくする'),
('port', 'root', '運ぶ', 'latin', ARRAY['transport', 'import', 'export', 'portable', 'report'], 'port=運ぶ。transport=向こうへ運ぶ、import=中に運ぶ、export=外に運ぶ'),
('scrib', 'root', '書く', 'latin', ARRAY['describe', 'prescribe', 'subscribe', 'manuscript', 'inscription'], 'scrib/script=書く。describe=下に書く=描写する、manuscript=手で書いたもの'),
('sent', 'root', '感じる', 'latin', ARRAY['sense', 'sentence', 'consent', 'sentiment', 'sensitive'], 'sent/sens=感じる。sense=感覚、sensitive=感じやすい、consent=共に感じる=同意'),
('spec', 'root', '見る', 'latin', ARRAY['inspect', 'spectacle', 'perspective', 'suspect', 'respect'], 'spec=見る。inspect=中を見る=検査、perspective=通して見る=視点'),
('struct', 'root', '建てる', 'latin', ARRAY['structure', 'construct', 'destroy', 'instruct', 'infrastructure'], 'struct=建てる。construct=共に建てる=建設、destroy=建てたものを壊す'),
('vid', 'root', '見る', 'latin', ARRAY['video', 'evidence', 'provide', 'visible', 'vision'], 'vid/vis=見る。video=見るもの、visible=見える、vision=見ること=視覚'),
('voc', 'root', '声・呼ぶ', 'latin', ARRAY['voice', 'vocabulary', 'vocal', 'advocate', 'provoke'], 'voc=声・呼ぶ。vocabulary=呼ぶための言葉集、advocate=呼びかける人'),
('bio', 'root', '生命', 'greek', ARRAY['biology', 'biography', 'antibiotic', 'biodiversity', 'biochemistry'], 'bio=生命。biology=生命の学問、biography=生命を書く=伝記'),
('geo', 'root', '地球・土地', 'greek', ARRAY['geography', 'geology', 'geometry', 'geopolitics', 'geocentric'], 'geo=地球。geography=地球を書く=地理、geology=地球の学問=地質学'),
('logos', 'root', '言葉・学問・理論', 'greek', ARRAY['logic', 'dialogue', 'monologue', 'prologue', 'epilogue'], 'logos=言葉・理由。logic=論理、dialogue=2人の言葉=対話'),
('cred', 'root', '信じる', 'latin', ARRAY['credit', 'incredible', 'credible', 'credential', 'creed'], 'cred=信じる。credit=信用、incredible=信じられない、credible=信頼できる'),
('fac', 'root', '作る・する', 'latin', ARRAY['factory', 'manufacture', 'facility', 'factor', 'artifact'], 'fac/fact/fect=作る。factory=作る場所、manufacture=手で作る'),
('ject', 'root', '投げる', 'latin', ARRAY['project', 'reject', 'inject', 'subject', 'object'], 'ject=投げる。project=前に投げる、reject=後ろに投げる=拒絶、inject=中に投げる=注射'),
('mit', 'root', '送る', 'latin', ARRAY['transmit', 'submit', 'permit', 'commit', 'admit'], 'mit/miss=送る。transmit=向こうへ送る=伝える、submit=下に送る=提出'),
('rupt', 'root', '壊す', 'latin', ARRAY['interrupt', 'corrupt', 'erupt', 'bankrupt', 'disrupt'], 'rupt=壊す。interrupt=間を壊す=中断、erupt=外に壊れる=噴火'),
('vers', 'root', '向く・回る', 'latin', ARRAY['universe', 'reverse', 'conversation', 'diverse', 'version'], 'vers/vert=回る。universe=1つに回る、reverse=後ろに回る、diverse=離れて回る=多様'),
('cap', 'root', '取る・頭', 'latin', ARRAY['capture', 'capable', 'capacity', 'capital', 'captain'], 'cap=取る/頭。capture=捕まえる、capital=頭の=首都、captain=頭の人=船長'),
('cept', 'root', '取る', 'latin', ARRAY['accept', 'concept', 'except', 'intercept', 'reception'], 'cept=取る(capの変形)。accept=向かって取る=受け入れる、concept=共に取る=概念'),
('cur', 'root', '走る・流れる', 'latin', ARRAY['current', 'occur', 'currency', 'curriculum', 'excursion'], 'cur/curs=走る。current=走っている=現在の/流れ、occur=向かって走る=起こる'),
('fin', 'root', '終わり・限界', 'latin', ARRAY['finish', 'final', 'define', 'infinite', 'finance'], 'fin=終わり。finish=終える、infinite=終わりがない=無限、define=限界を定める=定義する'),
('gen', 'root', '生む・種類', 'latin', ARRAY['generate', 'gene', 'genius', 'gentle', 'general'], 'gen=生む。generate=生み出す、gene=遺伝子、genius=生まれつきの才能'),
('ling', 'root', '言語・舌', 'latin', ARRAY['language', 'linguist', 'bilingual', 'multilingual', 'linguistics'], 'ling/lingua=舌・言語。linguist=言語の専門家、bilingual=2つの言語'),
('man', 'root', '手', 'latin', ARRAY['manual', 'manufacture', 'manage', 'manipulate', 'manuscript'], 'man/manu=手。manual=手の=手動の、manuscript=手で書いたもの=原稿'),
('nov', 'root', '新しい', 'latin', ARRAY['novel', 'innovation', 'novice', 'renovate', 'nova'], 'nov=新しい。novel=新しい=小説、innovation=中に新しくする=革新'),
('ped', 'root', '足', 'latin', ARRAY['pedal', 'pedestrian', 'centipede', 'expedition', 'impediment'], 'ped=足。pedal=足で踏む、pedestrian=足で歩く人、centipede=100の足=ムカデ'),
('phil', 'root', '愛する', 'greek', ARRAY['philosophy', 'philanthropy', 'bibliophile', 'Philadelphia'], 'phil=愛する。philosophy=知恵(sophia)を愛する、philanthropy=人類を愛する=慈善'),
('psych', 'root', '心・魂', 'greek', ARRAY['psychology', 'psychiatry', 'psychic', 'psychopath', 'psychedelic'], 'psych=心。psychology=心の学問、psychiatry=心の治療=精神医学'),
('scope', 'root', '見る', 'greek', ARRAY['microscope', 'telescope', 'horoscope', 'stethoscope', 'kaleidoscope'], 'scope=見る道具。microscope=小さいものを見る、telescope=遠くを見る'),
('terra', 'root', '地球・土地', 'latin', ARRAY['territory', 'terrain', 'terrace', 'terrestrial', 'extraterrestrial'], 'terra=土地。territory=土地の範囲=領土、terrestrial=地球の'),
('therm', 'root', '熱', 'greek', ARRAY['thermometer', 'thermal', 'thermostat', 'hypothermia', 'geothermal'], 'therm=熱。thermometer=熱を測る=温度計、thermal=熱の'),
('vit', 'root', '生命', 'latin', ARRAY['vital', 'vitamin', 'vitality', 'revitalize', 'survive'], 'vit/viv=生命。vital=生命の=重要な、vitamin=生命のアミン、survive=超えて生きる'),
('aqua', 'root', '水', 'latin', ARRAY['aquarium', 'aquatic', 'aqueduct', 'aquamarine'], 'aqua=水。aquarium=水の場所、aqueduct=水を導く=水道橋'),
('ast', 'root', '星', 'greek', ARRAY['astronomy', 'astronaut', 'asteroid', 'astrology', 'disaster'], 'ast/aster=星。astronaut=星の船乗り=宇宙飛行士、disaster=星が離れる=災害'),
('civ', 'root', '市民', 'latin', ARRAY['civil', 'civilization', 'civilian', 'civic', 'civility'], 'civ=市民。civilization=市民化=文明、civil=市民の'),
('dem', 'root', '人民', 'greek', ARRAY['democracy', 'epidemic', 'demographics', 'pandemic', 'endemic'], 'dem/demo=人民。democracy=人民の支配、epidemic=人民の上に=流行病'),
('jur', 'root', '法・誓い', 'latin', ARRAY['jury', 'justice', 'judge', 'injury', 'jurisdiction'], 'jur/jus=法・正義。jury=誓った人々=陪審、justice=正義、judge=法を言う人'),
('liber', 'root', '自由', 'latin', ARRAY['liberty', 'liberal', 'liberate', 'library', 'deliver'], 'liber=自由。liberty=自由、liberal=自由な、library=本の自由な場所(元は書物の意)'),
('mem', 'root', '記憶', 'latin', ARRAY['memory', 'remember', 'memorial', 'memo', 'memorable'], 'mem=記憶。memory=記憶、remember=再び記憶する、memorial=記憶のための'),
('nat', 'root', '生まれる', 'latin', ARRAY['nature', 'nation', 'native', 'natural', 'prenatal'], 'nat=生まれる。nature=生まれつきのもの=自然、nation=生まれた集団=国家'),
('opt', 'root', '目・見る / 最善', 'latin', ARRAY['optical', 'option', 'optimal', 'optimism', 'optician'], 'opt=見る/選ぶ。optical=目の、option=選択肢、optimal=最善の'),
('prim', 'root', '最初の', 'latin', ARRAY['primary', 'primitive', 'prime', 'prince', 'principal'], 'prim=最初。primary=最初の=主要な、prince=最初の者=王子'),
('sol', 'root', '太陽 / 一人', 'latin', ARRAY['solar', 'solitary', 'solo', 'solitude', 'console'], 'sol=太陽/一人。solar=太陽の、solo=一人で、solitary=孤独な'),
('temp', 'root', '時間', 'latin', ARRAY['temporary', 'contemporary', 'tempo', 'temporal', 'extemporaneous'], 'temp=時間。temporary=時間的な=一時的、contemporary=同じ時間の=現代の'),
('tract', 'root', '引く', 'latin', ARRAY['attract', 'extract', 'contract', 'distract', 'abstract'], 'tract=引く。attract=向かって引く=引きつける、extract=外に引く=抽出する')

ON CONFLICT (part, part_type) DO NOTHING;
